name: Milvasoft.Templates Nuget Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore Milvasoft.Templates project dependencies
        run: dotnet restore Milvasoft.Templates.csproj
      - name: Build Milvasoft.Templates project
        run: dotnet build Milvasoft.Templates.csproj --no-restore --configuration Release
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
